name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 212.85.25.129 >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /var/www/html/link-app

          git pull origin master

          composer install --no-dev --optimize-autoloader --ignore-platform-req=ext-fileinfo

          # run Artisan
          php artisan migrate --force
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear
          cd /var/www/html/link-app/socket

          pm2 restart all || pm2 start server.js --name socket-server

        EOF
