name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 212.85.25.129 >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh root@212.85.25.129 << 'EOF'
          # Chuyển đến thư mục dự án
          cd /var/www/html/link-app

          # Reset code và pull nhánh mới nhất
          git pull origin master

          # Cài đặt dependencies bằng Composer
          composer install --no-dev --optimize-autoloader

          # Thiết lập quyền cho thư mục storage và cache
          chown -R apache:apache /var/www/html/link-app
          chmod -R 775 storage bootstrap/cache

          # Chạy các lệnh Artisan
          php artisan migrate --force
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear
          php artisan optimize

        EOF
